version: "3.8"

services:
  express-mysql:
    image: mysql:8.2.0
    # restart: always
    container_name: express-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - express
    volumes:
      - db:/var/lib/mysql

  express-backend:
    image: express-backend
    # restart: always
    container_name: express-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    environment:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - express-mysql
    networks:
      - express
    ports:
      - 8000:8000

networks:
  express:
volumes:
  db:
